<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
	<xacro:include filename="$(find amr-ros-config)/urdf/materials.xacro"/>
	<xacro:include filename="$(find amr-ros-config)/urdf/inertial_macros.xacro"/>

	<xacro:macro name="pioneer3dx" params="prefix *origin">
		<!-- <xacro:include filename="$(find amr-ros-config)/urdf/pioneer3dx/pioneer3dx_wheel.xacro"/> -->

		<link name="${prefix}base_link">
    	</link>

		<!-- Base Link -->
		<xacro:property name="chassis_length" value="0.41"/>
		<xacro:property name="chassis_width" value="0.272"/>
		<xacro:property name="chassis_height" value="0.172"/>
		<link name="${prefix}real_base_link">
			<xacro:inertial_box mass="7.0" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            	<origin xyz="${-chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        	</xacro:inertial_box>
			<visual>
				<origin xyz="-0.045 0 0.148" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/chassis.stl"/>
				</geometry>
				<material name="ChassisRed"/>
			</visual>
			<!-- <collision>
				<origin xyz="-0.045 0 0.148" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/chassis.stl"/>
				</geometry>
			</collision> -->
		</link>

		<gazebo reference="${prefix}real_base_link">
			<material>Gazebo/Red</material>
		</gazebo>
		
		<joint name="${prefix}real_base_link_joint" type="fixed">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<parent link="${prefix}base_link"/>
			<child link="${prefix}real_base_link"/>
		</joint>

		<!-- Top Plate -->
		<xacro:property name="top_plate_length" value="0.41"/>
		<xacro:property name="top_plate_width" value="0.272"/>
		<xacro:property name="top_plate_height" value="0.0052"/>
		<link name="${prefix}top_plate">
			<xacro:inertial_box mass="0.1" x="${top_plate_length}" y="${top_plate_width}" z="${top_plate_height}">
            	<origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        	</xacro:inertial_box>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/top.stl"/>
				</geometry>
				<material name="TopBlack"/>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/top.stl"/>
				</geometry>
			</collision>
		</link>

		<gazebo reference="${prefix}top_plate">
			<material>Gazebo/Black</material>
		</gazebo>

		<joint name="${prefix}base_top_joint" type="fixed">
			<origin xyz="-0.045 0 0.234" rpy="0 0 0"/>
			<parent link="${prefix}real_base_link"/>
			<child link="${prefix}top_plate"/>
		</joint>

		<!-- Front Sonar -->
		<link name="${prefix}front_sonar">
			<inertial>
				<mass value="0.0001"/>	
				<origin xyz="0 0 0"/>
				<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/front_sonar.stl"/>
				</geometry>
				<material name="SonarYellow"/>
			</visual>
		</link>

		<gazebo reference="${prefix}front_sonar">
			<material value="Gazebo/Yellow"/>
		</gazebo>

		<joint name="${prefix}base_front_joint" type="fixed">
			<origin xyz="-0.198 0 0.208" rpy="0 0 0"/>
			<parent link="${prefix}real_base_link"/>
			<child link="${prefix}front_sonar"/>
		</joint>

		<!-- Back Sonar -->
		<joint name="${prefix}base_back_joint" type="fixed">
			<origin xyz="0.109 0 0.209" rpy="0 0 0"/>
			<parent link="${prefix}real_base_link"/>
			<child link="${prefix}back_sonar"/>
		</joint>

		<link name="${prefix}back_sonar">
			<inertial>
				<mass value="0.0001"/>	
				<origin xyz="0 0 0"/>
				<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/back_sonar.stl"/>
				</geometry>
				<material name="SonarYellow"/>
			</visual>
		</link>

		<gazebo reference="${prefix}back_sonar">
			<material value="Gazebo/Yellow"/>
		</gazebo>

		<!-- Caster Swivel -->
		<joint name="${prefix}base_caster_swivel_joint" type="fixed"> <!--Not fixed. Change for simulation -->
			<origin xyz="-0.185 0 0.055" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
			<parent link="${prefix}real_base_link"/>
			<child link="${prefix}caster_swivel"/>
			<limit effort="10000.0" lower="-100000" upper="100000" velocity="100000"/>
    		<!-- <dynamics damping="0.001" friction="0.0001"/> -->
		</joint>
		<passive_joint name="${prefix}base_caster_swivel_joint"/> <!--Not working -->

		<link name="${prefix}caster_swivel">
			<inertial>
				<mass value="0.01"/>	
				<origin xyz="0 0 0"/>
				<inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/caster_swivel.stl"/>
				</geometry>
				<material name="ChassisGrey"/>
			</visual>
			<!-- <collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/caster_swivel.stl"/>
				</geometry>
			</collision> -->
		</link>

		<gazebo reference="${prefix}caster_swivel">
			<material value="Gazebo/Grey"/>
		</gazebo>

		<!-- Center Wheel + Hubcap -->
		<link name="${prefix}caster_hubcap">
			<inertial>
				<mass value="0.01"/>	
				<origin xyz="0 0 0"/>
				<inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
							iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="${1.5708} 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/caster_hubcap.stl"/>
				</geometry>
				<material name="ChassisGrey"/>
			</visual>
			<!-- <collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/caster_hubcap.stl"/>
				</geometry>
			</collision> -->
		</link>

		<gazebo reference="${prefix}caster_hubcap">
			<material value="Gazebo/Grey"/>
		</gazebo>

		<joint name="${prefix}caster_swivel_hubcap_joint" type="fixed"> <!--Not fixed. Change for simulation -->
			<origin xyz="-0.026 0 -0.016" rpy="1.5708 0 0"/>
			<axis xyz="0 0 1"/>
			<parent link="${prefix}caster_swivel"/>
			<child link="${prefix}caster_hubcap"/>
			<limit effort="10000.0" lower="-100000" upper="100000" velocity="100000"/>
    		<!-- <dynamics damping="0.001" friction="0.0001"/> -->
		</joint>

		<!-- Caster Wheel -->
		<link name="${prefix}caster_wheel">
			<xacro:inertial_cylinder mass="0.2" length="0.01" radius="0.0375">
				<origin xyz="0 0 0" rpy="0 0 0"/>
			</xacro:inertial_cylinder>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="0.0375" length="0.01"/>
				</geometry>
				<material name="WheelBlack"/>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="0.0375" length="0.01"/>
				</geometry>
			</collision>
			<dynamics damping="10.0" friction="0"/>
		</link>

		<gazebo reference="${prefix}caster_wheel">
			<material value="Gazebo/Black"/>
		</gazebo>

		<joint name="${prefix}caster_wheel_joint" type="fixed">  <!--Not fixed. Change for simulation -->
			<origin xyz="-0.0035 0 -0.001" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
			<parent link="${prefix}caster_hubcap"/>
			<child link="${prefix}caster_wheel"/>
		</joint>
		
		<!-- Left Wheel -->
		<link name="${prefix}left_hub">
			<visual>
				<origin xyz="0 0 0" rpy="${-3.1415927/2.0} 0 0"/>
				<geometry>
					<cylinder radius="0.09" length="0.01"/>
				</geometry>
				<material name="HubcapYellow"/>
			</visual>
			<!-- <collision>
				<origin xyz="0 0 0" rpy="${-3.1415927/2.0} 0 0"/>
				<geometry>
					<cylinder radius="0.09" length="0.01"/>
				</geometry>
			</collision> -->
			<inertial>
				<mass value="0.1"/>
				<origin xyz="0 0 0" rpy="${-3.1415927/2.0} 0 0"/>
				<inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
			</inertial>
		</link>

		<gazebo reference="${prefix}left_hub">
			<material value="Gazebo/Yellow"/>
		</gazebo>


		<joint name="${prefix}left_hub_joint" type="fixed">
			<origin xyz="0 0.15 0.08" rpy="0 0 0"/>
			<parent link="${prefix}real_base_link"/>
			<child link="${prefix}left_hub"/>
			<axis xyz="0 1 0"/>
		</joint>

		<link name="${prefix}left_wheel">
			<visual>
				<origin xyz="0 0 0" rpy="1.5708 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/left_wheel.stl"/>
				</geometry>
				<material name="WheelBlack"/>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="0.09" length="0.04"/>
				</geometry>
			</collision>
			<xacro:inertial_cylinder mass="2.0" length="0.04" radius="0.09">
				<origin xyz="0 0 0" rpy="0 0 0"/>
			</xacro:inertial_cylinder>
			<dynamics damping="0" friction="10.0"/>
		</link>

		<gazebo reference="${prefix}left_wheel">
			<material value="Gazebo/Black"/>
		</gazebo>

		<joint name="${prefix}left_wheel_joint" type="continuous">
			<origin xyz="0 0 0" rpy="-1.5708 0 0"/>
			<axis xyz="0 0 1"/>
			<parent link="${prefix}left_hub"/>
			<child link="${prefix}left_wheel"/>
			<dynamics damping="0.001" friction="0.0001"/>
		</joint>

		<!-- Right Wheel -->
		<link name="${prefix}right_hub">
			<visual>
				<origin xyz="0 0 0" rpy="${3.1415927/2.0} 0 0"/>
				<geometry>
					<cylinder radius="0.09" length="0.01"/>
				</geometry>
				<material name="HubcapYellow"/>
			</visual>
			<!-- <collision>
				<origin xyz="0 0 0" rpy="${-3.1415927/2.0} 0 0"/>
				<geometry>
					<cylinder radius="0.06" length="0.04"/>
				</geometry>
			</collision> -->
			<inertial>
				<mass value="0.1"/>
				<origin xyz="0 0 0" rpy="${3.1415927/2.0} 0 0"/>
				<inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
			</inertial>
		</link>

		<gazebo reference="${prefix}right_hub">
			<material value="Gazebo/Yellow"/>
		</gazebo>

		<joint name="${prefix}right_hub_joint" type="fixed">
			<origin xyz="0 -0.15 0.08" rpy="0 0 0"/>
			<parent link="${prefix}real_base_link"/>
			<child link="${prefix}right_hub"/>
		</joint>

		<link name="${prefix}right_wheel">
			<visual>
				<origin xyz="0 0 0" rpy="-1.5708 0 0"/>
				<geometry>
					<mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/right_wheel.stl"/>
				</geometry>
				<material name="WheelBlack"/>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="0.09" length="0.04"/>
				</geometry>
			</collision>
			<xacro:inertial_cylinder mass="2.0" length="0.04" radius="0.09">
				<origin xyz="0 0 0" rpy="0 0 0"/>
			</xacro:inertial_cylinder>
			<dynamics damping="0" friction="10.0"/>
		</link>

		<gazebo reference="${prefix}right_wheel">
			<material value="Gazebo/Black"/>
		</gazebo>

		<joint name="${prefix}right_wheel_joint" type="continuous">
			<origin xyz="0 0 0" rpy="-1.5708 0 0"/>
			<axis xyz="0 0 1"/>
			<parent link="${prefix}right_hub"/>
			<child link="${prefix}right_wheel"/>
			<dynamics damping="0.001" friction="0.0001"/>
		</joint>


		
		<!-- Gazebo plugin -->
		<!-- <gazebo>
			<plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">

				<left_joint>${prefix}left_wheel_joint</left_joint>
				<right_joint>${prefix}right_wheel_joint</right_joint>

				<wheel_separation>0.3</wheel_separation>
				<wheel_diameter>0.12</wheel_diameter>

				<max_wheel_torque>200</max_wheel_torque>
				<max_wheel_acceleration>10.0</max_wheel_acceleration>

				<command_topic>cmd_vel</command_topic>

				<robot_base_frame>${prefix}real_base_link</robot_base_frame>
				<odometry_frame>${prefix}odom</odometry_frame>

				<publish_odom>true</publish_odom>
				<publish_odom_tf>true</publish_odom_tf>
				<publish_wheel_tf>true</publish_wheel_tf>

			</plugin>
		</gazebo> -->

	</xacro:macro>

</robot>
