<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from src/galax_robot/galax_bringup/urdf/galax.urdf.xacro | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="galax_robot">
  <material name="SonarYellow">
    <color rgba="0.715 0.583 0.210 1.0"/>
  </material>
  <material name="WheelBlack">
    <color rgba="0.117 0.117 0.117 1.0"/>
  </material>
  <material name="HubcapYellow">
    <color rgba="1.0 0.811 0.151 1.0"/>
  </material>
  <material name="ChassisRed">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  <material name="TopBlack">
    <color rgba="0.038 0.038 0.038 1.0"/>
  </material>
  <material name="ChassisGrey">
    <color rgba="0.47 0.47 0.47 1.0"/>
  </material>
  <!-- Specify some standard inertial calculations https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
  <!-- These make use of xacro's mathematical functionality -->
  <link name="pioneer3dx_base_link">
        </link>
  <!-- Chasis -->
  <link name="pioneer3dx_real_base_link">
    <!-- <collision>
                                <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
                                <geometry>
                                        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
                                </geometry>
                        </collision> -->
    <visual>
      <origin rpy="0 0 0" xyz="-0.045 0 0.148"/>
      <geometry>
        <mesh filename="file:///home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/meshes/p3dx_meshes/chassis.stl"/>
      </geometry>
      <material name="ChassisRed"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="-0.41 0 -0.172"/>
      <mass value="1.0"/>
      <inertia ixx="0.008630666666666667" ixy="0.0" ixz="0.0" iyy="0.016473666666666664" iyz="0.0" izz="0.020173666666666663"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_real_base_link">
    <material>Gazebo/Red</material>
  </gazebo>
  <joint name="pioneer3dx_real_base_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="pioneer3dx_base_link"/>
    <child link="pioneer3dx_real_base_link"/>
  </joint>
  <!-- Top Plate -->
  <link name="pioneer3dx_top_plate">
    <!-- <collision>
                                <origin xyz="${top_plate_length/2} 0 ${top_plate_height/2}"/>
                                <geometry>
                                        <box size="${top_plate_length} ${top_plate_width} ${top_plate_height}"/>
                                </geometry>
                        </collision> -->
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file:///home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/meshes/p3dx_meshes/top.stl"/>
      </geometry>
      <material name="TopBlack"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0026"/>
      <mass value="0.1"/>
      <inertia ixx="0.0006167586666666668" ixy="0.0" ixz="0.0" iyy="0.0014010586666666665" iyz="0.0" izz="0.0020173666666666664"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_top_plate">
    <material>Gazebo/Black</material>
  </gazebo>
  <joint name="pioneer3dx_base_top_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-0.045 0 0.234"/>
    <parent link="pioneer3dx_real_base_link"/>
    <child link="pioneer3dx_top_plate"/>
  </joint>
  <!-- Front Sonar -->
  <link name="pioneer3dx_front_sonar">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file:///home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/meshes/p3dx_meshes/front_sonar.stl"/>
      </geometry>
      <material name="SonarYellow"/>
    </visual>
    <inertial>
      <mass value="0.0001"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_front_sonar">
    <material value="Gazebo/Yellow"/>
  </gazebo>
  <joint name="pioneer3dx_base_front_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-0.198 0 0.208"/>
    <parent link="pioneer3dx_real_base_link"/>
    <child link="pioneer3dx_front_sonar"/>
  </joint>
  <!-- Back Sonar -->
  <link name="pioneer3dx_back_sonar">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file:///home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/meshes/p3dx_meshes/back_sonar.stl"/>
      </geometry>
      <material name="SonarYellow"/>
    </visual>
    <inertial>
      <mass value="0.0001"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_back_sonar">
    <material value="Gazebo/Yellow"/>
  </gazebo>
  <joint name="pioneer3dx_base_back_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.109 0 0.209"/>
    <parent link="pioneer3dx_real_base_link"/>
    <child link="pioneer3dx_back_sonar"/>
  </joint>
  <!-- Caster Swivel -->
  <link name="pioneer3dx_caster_swivel">
    <!-- <collision>
                                <origin xyz="0 0 0" rpy="0 0 0"/>
                                <geometry>
                                        <mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/caster_swivel.stl"/>
                                </geometry>
                        </collision> -->
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file:///home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/meshes/p3dx_meshes/caster_swivel.stl"/>
      </geometry>
      <material name="ChassisGrey"/>
    </visual>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_caster_swivel">
    <material value="Gazebo/Grey"/>
  </gazebo>
  <joint name="pioneer3dx_base_caster_swivel_joint" type="fixed">
    <!--Not fixed. Change for simulation -->
    <origin rpy="0 0 0" xyz="-0.185 0 0.055"/>
    <axis xyz="0 0 1"/>
    <parent link="pioneer3dx_real_base_link"/>
    <child link="pioneer3dx_caster_swivel"/>
  </joint>
  <!-- Hubcap -->
  <link name="pioneer3dx_caster_hubcap">
    <!-- <collision>
                                <origin xyz="0 0 0" rpy="0 0 0"/>
                                <geometry>
                                        <mesh filename="file://$(find amr-ros-config)/meshes/p3dx_meshes/caster_hubcap.stl"/>
                                </geometry>
                        </collision> -->
    <visual>
      <origin rpy="1.5708 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file:///home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/meshes/p3dx_meshes/caster_hubcap.stl"/>
      </geometry>
      <material name="ChassisGrey"/>
    </visual>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_caster_hubcap">
    <material value="Gazebo/Grey"/>
  </gazebo>
  <joint name="pioneer3dx_caster_swivel_hubcap_joint" type="fixed">
    <!--Not fixed. Change for simulation -->
    <origin rpy="1.5708 0 0" xyz="-0.026 0 -0.016"/>
    <axis xyz="0 0 1"/>
    <parent link="pioneer3dx_caster_swivel"/>
    <child link="pioneer3dx_caster_hubcap"/>
  </joint>
  <!-- Caster Wheel -->
  <link name="pioneer3dx_caster_wheel">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.0375"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.01" radius="0.0375"/>
      </geometry>
      <material name="WheelBlack"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.02"/>
      <inertia ixx="7.197916666666666e-06" ixy="0.0" ixz="0.0" iyy="7.197916666666666e-06" iyz="0.0" izz="1.40625e-05"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_caster_wheel">
    <material value="Gazebo/White"/>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </gazebo>
  <joint name="pioneer3dx_caster_wheel_joint" type="fixed">
    <!--Not fixed. Change for simulation -->
    <origin rpy="0 0 0" xyz="-0.0035 0 -0.001"/>
    <axis xyz="0 0 1"/>
    <parent link="pioneer3dx_caster_hubcap"/>
    <child link="pioneer3dx_caster_wheel"/>
  </joint>
  <!-- Left Wheel -->
  <link name="pioneer3dx_left_hub">
    <!-- <collision>
                                <origin xyz="0 0 0" rpy="${-3.1415927/2.0} 0 0"/>
                                <geometry>
                                        <cylinder radius="0.09" length="0.01"/>
                                </geometry>
                        </collision> -->
    <visual>
      <origin rpy="-1.57079635 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.01" radius="0.09"/>
      </geometry>
      <material name="HubcapYellow"/>
    </visual>
    <inertial>
      <origin rpy="-1.57079635 0 0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="3.598958333333333e-06" ixy="0.0" ixz="0.0" iyy="3.598958333333333e-06" iyz="0.0" izz="7.03125e-06"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_left_hub">
    <material value="Gazebo/Yellow"/>
  </gazebo>
  <joint name="pioneer3dx_left_hub_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.15 0.08"/>
    <parent link="pioneer3dx_real_base_link"/>
    <child link="pioneer3dx_left_hub"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="pioneer3dx_left_wheel">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.09"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="1.5708 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file:///home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/meshes/p3dx_meshes/left_wheel.stl"/>
      </geometry>
      <material name="WheelBlack"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.00021583333333333337" ixy="0.0" ixz="0.0" iyy="0.00021583333333333337" iyz="0.0" izz="0.000405"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_left_wheel">
    <material value="Gazebo/Black"/>
  </gazebo>
  <joint name="pioneer3dx_left_wheel_joint" type="continuous">
    <origin rpy="-1.5708 0 0" xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="pioneer3dx_left_hub"/>
    <child link="pioneer3dx_left_wheel"/>
  </joint>
  <!-- Right Wheel -->
  <link name="pioneer3dx_right_hub">
    <!-- <collision>
                                <origin xyz="0 0 0" rpy="${3.1415927/2.0} 0 0"/>
                                <geometry>
                                        <cylinder radius="0.09" length="0.01"/>
                                </geometry>
                        </collision> -->
    <visual>
      <origin rpy="1.57079635 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.01" radius="0.09"/>
      </geometry>
      <material name="HubcapYellow"/>
    </visual>
    <inertial>
      <origin rpy="1.57079635 0 0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="3.598958333333333e-06" ixy="0.0" ixz="0.0" iyy="3.598958333333333e-06" iyz="0.0" izz="7.03125e-06"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_right_hub">
    <material value="Gazebo/Yellow"/>
  </gazebo>
  <joint name="pioneer3dx_right_hub_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 -0.15 0.08"/>
    <parent link="pioneer3dx_real_base_link"/>
    <child link="pioneer3dx_right_hub"/>
  </joint>
  <link name="pioneer3dx_right_wheel">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.09"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="-1.5708 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file:///home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/meshes/p3dx_meshes/right_wheel.stl"/>
      </geometry>
      <material name="WheelBlack"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.00021583333333333337" ixy="0.0" ixz="0.0" iyy="0.00021583333333333337" iyz="0.0" izz="0.000405"/>
    </inertial>
  </link>
  <gazebo reference="pioneer3dx_right_wheel">
    <material value="Gazebo/Black"/>
  </gazebo>
  <joint name="pioneer3dx_right_wheel_joint" type="continuous">
    <origin rpy="1.5708 0 0" xyz="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <parent link="pioneer3dx_right_hub"/>
    <child link="pioneer3dx_right_wheel"/>
  </joint>
  <gazebo>
    <plugin filename="libgazebo_ros_diff_drive.so" name="diff_drive">
      <!-- Wheel Information -->
      <left_joint>pioneer3dx_left_wheel_joint</left_joint>
      <right_joint>pioneer3dx_right_wheel_joint</right_joint>
      <wheel_separation>0.30</wheel_separation>
      <wheel_diameter>0.18</wheel_diameter>
      <!-- Limits -->
      <max_wheel_torque>200</max_wheel_torque>
      <max_wheel_acceleration>10.0</max_wheel_acceleration>
      <!-- Output -->
      <odometry_frame>pioneer3dx_odom</odometry_frame>
      <robot_base_frame>pioneer3dx_base_link</robot_base_frame>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
    </plugin>
  </gazebo>
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="pioneer3dx_left_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
    <joint name="pioneer3dx_right_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
  </ros2_control>
  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>/home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/config/controller_config.yaml</parameters>
      <parameters>/home/pep/pioneer3_ws/install/amr-ros-config/share/amr-ros-config/config/gaz_ros2_ctl_use_sim.yaml</parameters>
    </plugin>
  </gazebo>
  <material name="dark_grey">
    <color rgba="0.3 0.3 0.3 1"/>
  </material>
  <!-- Create a base_link and use the macro -->
  <!-- <link name="base_link"/> -->
  <!-- Example usage of the macro -->
  <!-- <xacro:hokuyo_ust10_mount prefix="laser" topic="scan" parent_link="base_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:hokuyo_ust10_mount> -->
  <link name="hokuyo_laser">
    <inertial>
      <mass value="1.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.00307156543804" ixy="0.0" ixz="0.0" iyy="0.0031284904152700005" iyz="0.0" izz="0.00196432421427"/>
    </inertial>
  </link>
  <gazebo reference="hokuyo_laser">
    <turnGravityOff>true</turnGravityOff>
    <sensor name="hokuyo_laser" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>120</samples>
            <resolution>1</resolution>
            <min_angle>-2.35619</min_angle>
            <max_angle>2.35619</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.001</stddev>
        </noise>
      </ray>
      <plugin filename="libgazebo_ros_ray_sensor.so" name="gazebo_ros_laser">
        <ros>
          <namespace>/</namespace>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>hokuyo_laser</frame_name>
      </plugin>
    </sensor>
  </gazebo>
  <joint name="hokuyo_laser_mount_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.16 0 0"/>
    <parent link="pioneer3dx_top_plate"/>
    <child link="hokuyo_laser_mount"/>
  </joint>
  <link name="hokuyo_laser_mount">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <!-- Origin of this mesh is the base of the bracket. -->
        <mesh filename="file:///home/pep/pioneer3_ws/install/urg_node/share/urg_node/meshes/hokuyo_ust10.stl"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
  </link>
  <joint name="hokuyo_laser_joint" type="fixed">
    <!-- This offset is from the base of the bracket to the LIDAR's focal point. -->
    <origin rpy="0 0 0" xyz="0 0 0.0474"/>
    <parent link="hokuyo_laser_mount"/>
    <child link="hokuyo_laser"/>
  </joint>
  <gazebo reference="hokuyo_laser_mount">
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <!-- COLLISION DETECTOR -->
  <!-- <xacro:if value="$(arg sim_mode)">
    <xacro:include filename="$(find amr-ros-config)/urdf/pioneer3dx/gazebo_contact.xacro"/>
    <xacro:pioneer3dx_collision_controller prefix="pioneer3dx_" link_name="base_link"/>
  </xacro:if> -->
</robot>